# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/npm.gitlab-ci.yml

stages:          # List of stages for jobs, and their order of execution
  - build
  - test
  - deploy

build:       # This job runs in the build stage, which runs first.
  stage: build
  image: node:latest
  script:
    - echo "Node compile started"
    - "npm install"
    - "npm install -g netlify-cli --unsafe-perm=true"
    - "CI=false npm run build"

  artifacts:      
    paths:
      - build
      - node_modules/

test:   # This job runs in the test stage.
  stage: test         # It only starts when the job in the build stage completes successfully.
  image: node:latest
  script:
    - echo "Node test started"
    - npm test

deploy:
  stage: deploy
  image: node:latest
  script: 
    - npx netlify-cli deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_AUTH_TOKEN --prod